version: "3.9"
services:
  db:
    image: postgres:15
    container_name: reviews_postgres
    restart: always
    environment:
      POSTGRES_USER: trustuser
      POSTGRES_PASSWORD: trustpass
      POSTGRES_DB: reviews
      DATABASE_URL: postgres://trustuser:trustpass@localhost:5432/reviews
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: reviews_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://trustuser:trustpass@db:5432/reviews
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
