from app.constants import (
    F_IP, F_REVIEW_ID, F_USER_ID, F_BUSINESS_ID, F_RATING, F_TITLE,
    F_TEXT, F_CREATED_AT, F_USER_NAME, F_BUSINESS_NAME, F_EMAIL
)

HEADERS = {
    "reviews": [F_REVIEW_ID, F_USER_ID, F_BUSINESS_ID, F_RATING, F_TITLE, F_TEXT, F_IP, F_CREATED_AT],
    "users": [F_USER_ID, F_USER_NAME, F_EMAIL],
    "reviews_expanded": [
        F_REVIEW_ID, F_RATING, F_TITLE, F_TEXT, F_IP, F_CREATED_AT,
        F_USER_ID, F_USER_NAME, F_EMAIL,
        F_BUSINESS_ID, F_BUSINESS_NAME,
    ],
}
