name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: trustuser
          POSTGRES_PASSWORD: trustpass
          POSTGRES_DB: reviews
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U trustuser -d reviews"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (SQLite)
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Run tests (Postgres)
        env:
          DATABASE_URL: postgres://trustuser:trustpass@localhost:5432/reviews
        run: pytest --maxfail=1 --disable-warnings -q

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
